spring:
  cloud:
    gateway:
      routes:
        - id: library-mvc-project
          uri: http://library-mvc-project:2010
          predicates:
            - Path=/library/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.DispatcherHandler: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
